name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

env:
  TAILWIND_REBUILD: 1
  TAILWIND_BIN: tailwindcss

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.REGISTRY }}/${{ gitea.repository }}/ci:latest
      options: "-v /srv/cache/cargo-registry:/root/.cargo/registry -v /srv/cache/cargo-git:/root/.cargo/git"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo check
        run: cargo check --all-targets
      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run cargo test
        run: cargo test